coverage:
  round: nearest
  ignore:
    - http3/gzip_reader.go
    - interop/
    - internal/handshake/cipher_suite.go
    - internal/utils/linkedlist/linkedlist.go
    - logging/null_tracer.go
    - fuzzing/
    - metrics/
    - "**/mockgen.go"
  status:
    project:
      default:
        threshold: 0.5
    patch: false
